name: _debug-called

on:
  workflow_call:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        env:
          GH_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "event_name=$GITHUB_EVENT_NAME"
          echo "$GH_CONTEXT"
